### ISSUE TITLE
Recommendation for state access in composables (warnings in todo-example)

### ISSUE THREAD

**Issue by jonekdahl** [toggl/komposable-architecture#25]
Hi there,

Thank you so much for making this! I'm pretty new to Android development, and I have a question regarding the todo-example. In the Page composables there are warnings that say `Flow operator functions should not be invoked within composition`. Can these safely be ignored, or is there some other pattern that should be use when accessing state in a composable?

![image](https://user-images.githubusercontent.com/595004/151850117-2a63cc73-6e4a-4d2c-bfa9-2ae1c4cc41cc.png)

**Comment by heytherewill** [comment]
Hey there!

My personal predilection would be to `store.state.collectAsState(initial = State())` and then use the bits of state in a completely imperative way, leaving it up for Compose to figure out when the recomposition should happen. 

In an ideal scenario you'd isolate your Composables so that each only take the smallest bit of state they need to render. That would make it easier for you to understand what dependencies cause the recomposition of what :)

**Comment by jonekdahl** [comment]
Hi @heytherewill,

Thanks for trying to help, I really appreciate it! I tried to apply your suggestion to the `EditState`, just wanted to make sure that this is what you are proposing? I a bit concerned about initializing global state such as the `backStack` at this level.

```diff
--- a/todo-sample/src/main/java/com/toggl/komposable/sample/todo/edit/EditPage.kt
+++ b/todo-sample/src/main/java/com/toggl/komposable/sample/todo/edit/EditPage.kt
@@ -11,17 +11,18 @@ import androidx.compose.material.MaterialTheme
 import androidx.compose.material.Text
 import androidx.compose.material.TextField
 import androidx.compose.runtime.Composable
 import androidx.compose.runtime.collectAsState
 import androidx.compose.ui.Modifier
 import androidx.compose.ui.unit.dp
 import androidx.hilt.navigation.compose.hiltViewModel
 import com.toggl.komposable.sample.todo.data.EditableTodoItem
-import kotlinx.coroutines.flow.map
 
 @Composable
 fun EditPage() {
     val store = hiltViewModel<EditStoreViewModel>()
-    val editableTodoItem = store.state.map { it.editableTodo }.collectAsState(initial = EditableTodoItem())
+    val state = store.state.collectAsState(initial = EditState(editableTodo = EditableTodoItem(), backStack = emptyList()))
+    val editableTodoItem = state.value.editableTodo
     Column(
         modifier = Modifier.padding(horizontal = 16.dp, vertical = 32.dp).fillMaxSize(),
     ) {
@@ -33,7 +34,7 @@ fun EditPage() {
         TextField(
             modifier = Modifier.fillMaxWidth(),
             label = { Text("Title") },
 
 @Composable
 fun EditPage() {
     val store = hiltViewModel<EditStoreViewModel>()
-    val editableTodoItem = store.state.map { it.editableTodo }.collectAsState(initial = EditableTodoItem())
+    val state = store.state.collectAsState(initial = EditState(editableTodo = EditableTodoItem(), backStack = emptyList()))
+    val editableTodoItem = state.value.editableTodo
     Column(
         modifier = Modifier.padding(horizontal = 16.dp, vertical = 32.dp).fillMaxSize(),
     ) {
@@ -33,7 +34,7 @@ fun EditPage() {
         TextField(
             modifier = Modifier.fillMaxWidth(),
             label = { Text("Title") },
-            value = editableTodoItem.value.title,
+            value = editableTodoItem.title,
             onValueChange = { store.dispatch(EditAction.TitleChanged(it)) },
             singleLine = true
         )
@@ -41,7 +42,7 @@ fun EditPage() {
         TextField(
             modifier = Modifier.fillMaxWidth().fillMaxHeight(0.5f),
             label = { Text("Description") },
-            value = editableTodoItem.value.description,
+            value = editableTodoItem.description,
             onValueChange = { store.dispatch(EditAction.DescriptionChanged(it)) },
             maxLines = 20
         )
```

**Comment by heytherewill** [comment]
The gist is that you are not really initializing global state: The parameter you supply there is merely for the Kotlin compiler to satisfy the constraint of having **some** initial state. The compiler can't assert that because Flows might not have emitted by that time. Given that the library enforces the initial state is always available in the `state` flow, the parameter passed to `collectAsState` won't ever be needed.

**Comment by jonekdahl** [comment]
Thanks @heytherewill , I think I get what you're saying.

Closing this issue, since Wills suggestion seems to be working.
