### ISSUE TITLE
Jetpack navigation plan

### ISSUE THREAD

**Issue by jonekdahl** [toggl/komposable-architecture#26]
From the README:

> we are thinking about ways to integrate jetpack navigation

What is the plan for this?

**Comment by semanticer** [comment]
We're currently experimenting with multiple different ideas regarding this. Internally, we use some representation of backstack in the AppState. This backstack is then observed and translated to navigation actions. However, this approach is duplicating some of the work done in the Jetpack Navigation component. Ideally, we'd like to provide some way of navigating from reducers without this duplication. We're open to any ideas.

**Comment by jonekdahl** [comment]
Yeah, we couldn't really understand the benefit of keeping the backstack in the AppState so we removed it in our app.
